### ISSUE TITLE
ubuntuone link is dead

### ISSUE THREAD

**Issue by skorasaurus** [hotosm/HDM-JOSM-style#63]
ubuntuone closed down at beginning of june so the link is dead. 

Do we even need to host somewhere else or should we assume that people have updated to JOSM version 6152 (which allows people to load the HDM JOSM style through their preferences). 

see: https://github.com/hotosm/HDM-JOSM-style/issues/12 
for background information.

**Comment by boukepieter** [comment]
I also found this out which made it harder to install in JOSM. At http://hot.openstreetmap.org/updates/hdmjosm it is still explained to use this link. Maybe this should be changed. But somewhere else I found your very clear 'installation guide': http://gis.19327.n5.nabble.com/Do-you-know-about-HOT-s-preset-amp-Map-Style-for-JOSM-td5801031.html
Maybe you can say something like this on the first page or on this wiki?

**Comment by skorasaurus** [comment]
Thank you for reminding me about this; I'll make a pull request to fix this tonight.

**Comment by yohanboniface** [comment]
Fixed with #66 thanks to @skorasaurus :)
