### ISSUE TITLE
E: Failed to locate image 'icons/hot_small.png'

### ISSUE THREAD

**Issue by yohanboniface** [hotosm/HDM-JOSM-style#64]
Reported on IRC.

The file doesn't seem to be missing, so I've no clue.

**Comment by skorasaurus** [comment]
I was unable to reproduce this bug after I made a new profile (.josm folder) for JOSM. 

There's plenty of other icons that are reported missing in the JOSM console, but not this one ;)  

Mark as closed.

**Comment by yohanboniface** [comment]
ok :)
