### ISSUE TITLE
Wrong icon names

### ISSUE THREAD

**Issue by Klumbumbus** [hotosm/HDM-JOSM-style#68]
There are some icon, where the file name differs from the filename in the mapcss file.

    ERROR: Failed to locate image 'icons/marketplace-18.png'
    WARNING: Mappaint style "standard" (HDM) icon "icons/marketplace-18.png" not found.
    ERROR: Failed to locate image 'icons/bus_stop.png'
    WARNING: Mappaint style "standard" (HDM) icon "icons/bus_stop.png" not found.
    ERROR: Failed to locate image 'icons/communication_tower-18.png'
    WARNING: Mappaint style "standard" (HDM) icon "icons/communication_tower-18.png" not found.

Such errors are now automatically detected by josm e.g. here https://josm.openstreetmap.de/jenkins/job/JOSM/665/jdk=JDK8/testReport/junit/org.openstreetmap.josm.gui.preferences.map/MapPaintPreferenceTest/testValidityOfAvailableStyles/

**Comment by don-vip** [comment]
See #67 :)

**Comment by yohanboniface** [comment]
Thanks @don-vip :)

Someone really needs (me?) to jump in maintaining this project again! :)
