### ISSUE TITLE
changed icon paths

### ISSUE THREAD

**Issue by Klumbumbus** [hotosm/HDM-JOSM-style#69]
JOSM has [moved](https://josm.openstreetmap.de/ticket/13084#comment:21) some icons and this style needs an update.
The restriction icon paths at the beginning starting with "vehicle/restriction/..." start now with "presets/vehicle/restriction/..."

**Comment by yohanboniface** [comment]
Can you provide a pull request with such changes by chance?

**Comment by Klumbumbus** [comment]
That was my first github pull request. Was all correct?
